spring.application.name=personal-finance-management

# HIKARI
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.idleTimeout=20000
spring.datasource.hikari.connectionTimeout=30000

# DATA-SOURCE
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true

# OPEN-API
com.personalfinance.management.swagger.properties.title=RESTful API Personal Finance Management
com.personalfinance.management.swagger.properties.description=OpenAPI for Personal Finance Management, with the following features:\n\
  1. User management\n\
  2. Income management\n\
  3. Expenses management\n\
  4. Monthly spending limit\n\
  5. Monthly spending summary\n\
  6. Savings management\n\
  7. Dashboard display
com.personalfinance.management.swagger.properties.api-version=1.0.0
com.personalfinance.management.swagger.properties.contact.name=Mahfudz Nur Fadhila
com.personalfinance.management.swagger.properties.contact.email=mahfudnf63@gmail.com
com.personalfinance.management.swagger.properties.contact.url=linkedin.com/in/mahfud-n-f-b555b2260
com.personalfinance.management.swagger.properties.security.name=AuthenticationBearer
com.personalfinance.management.swagger.properties.security.scheme=bearer
com.personalfinance.management.swagger.properties.security.bearer-format=JWT

# JWT
com.personalfinance.management.jwt.secret-key=${JWT_SECRET_KEY}
com.personalfinance.management.jwt.expiration-time=3600000